(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'), canvas=$('#gameCanvas'), ctx=canvas.getContext('2d'), dCanvas=$('#designerCanvas'), dctx=dCanvas.getContext('2d');
const W=960,H=600; canvas.width=W; canvas.height=H;

const imageFiles={ping:'assets/ping.png',crash:'assets/crash.png',null:'assets/null.png',alonewood:'assets/alonewood.png',bluescreen:'assets/bluescreen.png',enemy:'assets/enemy.png',tanker:'assets/enemytanker.png',rusher:'assets/enemyrusher.png',unusedunloved:'assets/unusedunloved.png',changeme00:'assets/changeme00.png',thinkingcrystals:'assets/thinkingcrystals.png',sculpturedemon:'assets/sculpturedemon.png',inficookie:'assets/inficookie.png',bleedbot:'assets/bleedbot.png',pumpkiller:'assets/pumpkiller.png',lobberninja:'assets/lobberninja.png'};
const images={}; for(const [k,s] of Object.entries(imageFiles)){const im=new Image();im.src=s;images[k]=im;}

const TOWERS={
 ping:{name:'PING',cost:50,range:135,rate:.25,damage:16,projectile:590,desc:'fast shots'},
 crash:{name:'CRASH',cost:90,range:155,rate:.88,damage:36,projectile:390,splash:62,desc:'area damage'},
 null:{name:'NULL',cost:125,range:180,rate:1.12,damage:76,projectile:450,slow:.56,desc:'heavy + slow'},
 alonewood:{name:'ALONEWOOD',cost:100,range:305,rate:.17,damage:3.5,projectile:700,desc:'huge range / chip'},
 bluescreen:{name:'BLUESCREEN',cost:220,range:380,rate:7,damage:280,rail:true,desc:'7s piercing railgun'},
 inficookie:{name:'INFICOOKIE',cost:35,range:150,rate:.20,damage:2.2,projectile:640,desc:'cheap rapid fire'},
 bleedbot:{name:'BLEEDBOT',cost:55,range:155,rate:1.30,damage:4,projectile:420,bleed:{damage:2,duration:4},desc:'bleed damage'},
 pumpkiller:{name:'PUMPKILLER',cost:70,range:92,rate:1.72,damage:48,projectile:520,desc:'close burst'},
 lobberninja:{name:'LOBBER NINJA',cost:80,range:245,rate:1.75,damage:28,projectile:255,splash:48,lob:true,desc:'long splash lob'},
 brick:{name:'BRICK',cost:45,range:110,rate:1.05,damage:32,projectile:420,desc:'cheap solid hit',proc:'#d98354'},
 needle:{name:'NEEDLE',cost:60,range:230,rate:.72,damage:18,projectile:760,pierce:2,desc:'thin piercing shot',proc:'#d8d8d8'},
 splashbox:{name:'SPLASHBOX',cost:95,range:165,rate:1.35,damage:30,projectile:360,splash:88,desc:'wide splash',proc:'#50bf8a'},
 relay:{name:'RELAY',cost:110,range:185,rate:.85,damage:22,projectile:500,chain:3,desc:'chains between enemies',proc:'#78d8ff'},
 ticker:{name:'TICKER',cost:75,range:145,rate:.40,damage:9,projectile:620,crit:.18,desc:'sometimes hits hard',proc:'#ffe260'},
 orbit:{name:'ORBIT',cost:130,range:130,rate:.55,damage:20,aoeSelf:true,desc:'hits all nearby',proc:'#9d72dd'},
 crumbler:{name:'CRUMBLER',cost:85,range:170,rate:1.10,damage:14,projectile:430,armorBreak:.10,desc:'breaks armor',proc:'#ba8a5d'},
 snare:{name:'SNARE',cost:70,range:175,rate:1.0,damage:5,projectile:430,slow:.42,slowTime:2.4,desc:'strong slow',proc:'#71b7a5'},
 burstglass:{name:'BURSTGLASS',cost:145,range:205,rate:2.4,damage:105,projectile:610,desc:'slow heavy shot',proc:'#ff8db8'},
 longhand:{name:'LONGHAND',cost:160,range:420,rate:2.2,damage:72,projectile:900,desc:'very long range',proc:'#86a2ff'}
};

const ENEMIES={
 enemy:{hp:1,speed:1,reward:1,scale:1,color:'#f0222b'},tanker:{hp:1.7,speed:.65,reward:1.45,scale:1.15,color:'#ff7c86'},rusher:{hp:.5,speed:1.45,reward:.9,scale:.9,color:'#ff2835'},
 unusedunloved:{hp:1.2,speed:.8,reward:.75,scale:1.05,color:'#25b85a'},changeme00:{hp:1,speed:1,reward:1.1,scale:1.02,color:'#8fd9ea'},thinkingcrystals:{hp:1.05,speed:.85,reward:1.28,scale:1.08,color:'#8adcf0'},sculpturedemon:{hp:1.35,speed:.72,reward:1.6,scale:1.22,color:'#b05abb'},
 paperclip:{hp:.75,speed:1.3,reward:.95,scale:.82,color:'#d5d5d5',proc:'clip'},clot:{hp:1.45,speed:.72,reward:1.35,scale:1.12,color:'#992c42',proc:'clot'},zipper:{hp:.7,speed:1.55,reward:1,scale:.88,color:'#e7df6a',proc:'zip'},mirror:{hp:1.15,speed:.9,reward:1.35,scale:1.05,color:'#9fc7ff',proc:'mirror',reflect:.12},healer:{hp:1.05,speed:.82,reward:1.45,scale:1.02,color:'#68d88a',proc:'plus',heal:true},splitter:{hp:.95,speed:1.0,reward:1.3,scale:1.05,color:'#ff9c59',proc:'split',split:true},ghost:{hp:.82,speed:1.1,reward:1.2,scale:1,color:'#b8b8e8',proc:'ghost',phase:true},leech:{hp:1.2,speed:.86,reward:1.5,scale:1.08,color:'#791a2c',proc:'leech'},brickhead:{hp:1.8,speed:.58,reward:1.55,scale:1.18,color:'#a87655',proc:'brick'},phase:{hp:1.0,speed:1.18,reward:1.4,scale:1,color:'#8a6cff',proc:'phase',phase:true}
};

const DIFF={easy:{name:'EASY',hp:.65,speed:.9,cash:1.1,count:1,gap:1,armor:.02,bars:.01},normal:{name:'NORMAL',hp:1,speed:1,cash:1,count:1,gap:1,armor:.06,bars:.04},hard:{name:'HARD',hp:1.35,speed:1.08,cash:1,count:1.05,gap:1,armor:.10,bars:.07},insane:{name:'INSANE',hp:1.75,speed:1.15,cash:1,count:1.1,gap:.96,armor:.15,bars:.10},ultra:{name:'ULTRA',hp:2.4,speed:1.22,cash:1,count:1.15,gap:.94,armor:.22,bars:.16},nightmare:{name:'NIGHTMARE',hpMin:3,hpMax:4.25,speedMin:1.22,speedMax:1.38,cash:1,count:1.25,gap:.9,armor:.3,bars:.24},fun:{name:'FUN MODE',hp:5.5,speed:.85,cash:1,count:2,gap:1.35,armor:.38,bars:.33,noSell:true}};

const defaults={shake:true,flashes:true,particles:'full',sound:true,damageNumbers:true,healthBars:true,confirmSell:false};
let settings=loadJSON('unrendered_settings',defaults), profile=loadJSON('unrendered_profile',{points:0,baseHP:20,damage:0,range:0,rate:0,sell:0,clears:{}});
profile.baseHP=Math.min(9999,Math.max(20,profile.baseHP||20));
let selectedDifficulty=localStorage.getItem('unrendered_difficulty')||'normal'; if(!DIFF[selectedDifficulty])selectedDifficulty='normal';
let state=null, selectedTower='ping',towerPage=0,raf=0,last=performance.now(),shake=0,audioCtx=null,customLevels=loadArray('unrendered_custom_levels'),designerPath=[[-.03,.5],[.2,.5],[.45,.28],[.68,.7],[1.03,.52]],endless={active:false,cleared:0,lastWaveKey:''};
const towerPerPage=5;
function loadJSON(k,f){try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return JSON.parse(JSON.stringify(f))}}
function loadArray(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function saveProfile(){localStorage.setItem('unrendered_profile',JSON.stringify(profile));refreshPoints();}
function saveSettings(){localStorage.setItem('unrendered_settings',JSON.stringify(settings));}
function refreshPoints(){['homePoints','upgradePoints','gamePoints'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=Math.floor(profile.points||0)});}
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));if(id!=='gameScreen')cancelAnimationFrame(raf);if(id==='designerScreen')requestAnimationFrame(drawDesigner);if(id==='upgradesScreen')renderUpgrades();if(id==='settingsScreen')renderSettings();}
function ensureAudio(){if(!settings.sound)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch{}}
function tone(f=300,d=.05,v=.015,type='square',end=null){if(!settings.sound)return;ensureAudio();if(!audioCtx)return;const n=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,n);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),n+d);g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(audioCtx.destination);o.start(n);o.stop(n+d);}
function toast(t,ms=1100){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),ms)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function allLevels(){return [...UNRENDERED_LEVELS,...customLevels]}
function pathsOf(lvl){return lvl.paths?.length?lvl.paths:[lvl.path]}

function renderDifficulty(){const box=$('#difficultyButtons');box.innerHTML='';for(const [k,d] of Object.entries(DIFF)){const b=document.createElement('button');b.className='difficulty-btn'+(k===selectedDifficulty?' active':'');b.textContent=d.name;b.onclick=()=>{selectedDifficulty=k;localStorage.setItem('unrendered_difficulty',k);renderDifficulty()};box.appendChild(b)}const d=DIFF[selectedDifficulty];$('#difficultyInfo').textContent=kinfo(selectedDifficulty,d);}
function kinfo(k,d){if(k==='nightmare')return'300–425% HP // armor and extra health bars are common';if(k==='fun')return'550% HP // double enemies // slower enemies and wave pacing // no selling';return`${Math.round(d.hp*100)}% HP // ${Math.round(d.speed*100)}% speed`;}
function renderLevels(){const host=$('#worldList');host.innerHTML='';for(const world of UNRENDERED_WORLDS){const sec=document.createElement('section');sec.className='world-section';const levels=allLevels().filter(l=>(l.world||1)===world.id&&!l.custom);sec.innerHTML=`<div class="world-heading"><div><h3>${world.name}</h3><p>${world.description}</p></div><div class="world-progress">${levels.length}/${world.levelCount} LEVELS</div></div>`;const grid=document.createElement('div');grid.className='level-grid';levels.forEach((l,i)=>grid.appendChild(levelCard(l,allLevels().indexOf(l),i+1)));sec.appendChild(grid);host.appendChild(sec)}const custom=allLevels().filter(l=>l.custom);if(custom.length){const sec=document.createElement('section');sec.className='world-section';sec.innerHTML='<div class="world-heading"><div><h3>CUSTOM</h3></div></div>';const grid=document.createElement('div');grid.className='level-grid';custom.forEach((l,i)=>grid.appendChild(levelCard(l,allLevels().indexOf(l),i+1)));sec.appendChild(grid);host.appendChild(sec)}renderDifficulty();}
function levelCard(l,idx,n){const c=document.createElement('article');c.className='level-card';const ps=pathsOf(l);const lines=ps.map(p=>`<polyline points="${p.map(q=>`${Math.round(5+q[0]*90)},${Math.round(8+q[1]*72)}`).join(' ')}" fill="none" stroke="${l.tint||'#0aa1e8'}" stroke-width="2.5"/>`).join('');c.innerHTML=`<div class="num">${String(n).padStart(2,'0')}</div><svg class="mini-path" viewBox="0 0 100 80">${lines}</svg><h3>${escapeHtml(l.name)}</h3><p>${escapeHtml(l.description||'')}</p><div class="meta">${l.waves.length} WAVES // ${ps.length} PATH${ps.length>1?'S':''} // $${l.startCash}</div>`;c.onclick=()=>{endless.active=false;startLevel(idx)};return c;}

function rollDiff(){const d=DIFF[selectedDifficulty];if(selectedDifficulty==='nightmare')return{...d,hp:d.hpMin+Math.random()*(d.hpMax-d.hpMin),speed:d.speedMin+Math.random()*(d.speedMax-d.speedMin)};return{...d};}
function baseUpgradeCost(){return Math.max(2,Math.floor(3+Math.pow((profile.baseHP-20)/12,1.18)));}
function renderUpgrades(){refreshPoints();const host=$('#upgradeList');host.innerHTML='';const defs=[
 {id:'base',name:'BASE HEALTH',desc:`Starts every base at ${profile.baseHP} HP. Maximum 9999.`,cost:baseUpgradeCost(),buy(){if(profile.baseHP>=9999)return false;profile.baseHP=Math.min(9999,profile.baseHP+10);return true}},
 {id:'damage',name:'UNIT DAMAGE',desc:`+${profile.damage*2}% all unit damage.`,cost:8+profile.damage*5,buy(){profile.damage++;return true}},
 {id:'range',name:'UNIT RANGE',desc:`+${profile.range*1.5}% all unit range.`,cost:8+profile.range*5,buy(){profile.range++;return true}},
 {id:'rate',name:'FIRE RATE',desc:`+${profile.rate*1.5}% attack speed.`,cost:10+profile.rate*6,buy(){profile.rate++;return true}},
 {id:'sell',name:'SELL REFUND',desc:`${Math.min(90,70+profile.sell*2)}% refund outside Fun Mode.`,cost:12+profile.sell*8,buy(){if(profile.sell>=10)return false;profile.sell++;return true}}
 ];
 for(const d of defs){const row=document.createElement('div');row.className='upgrade-row';row.innerHTML=`<div><h3>${d.name}</h3><p>${d.desc}</p></div><button>${d.id==='base'&&profile.baseHP>=9999?'MAX':d.cost+' P'}</button>`;row.querySelector('button').onclick=()=>{if(d.id==='base'&&profile.baseHP>=9999)return;if(profile.points<d.cost)return toast('NOT ENOUGH POINTS');if(!d.buy())return;profile.points-=d.cost;saveProfile();renderUpgrades();tone(600,.08,.01,'sine',820)};host.appendChild(row)}
}
function renderSettings(){const host=$('#settingsList');host.innerHTML='';const rows=[['shake','SCREEN SHAKE',['ON','OFF']],['flashes','FLASHING EFFECTS',['ON','OFF']],['sound','SOUND EFFECTS',['ON','OFF']],['damageNumbers','DAMAGE NUMBERS',['ON','OFF']],['healthBars','ENEMY HEALTH BARS',['ON','OFF']],['confirmSell','CONFIRM SELL',['ON','OFF']],['particles','PARTICLES',['FULL','REDUCED','MINIMAL']]];for(const [key,name,opts] of rows){const row=document.createElement('div');row.className='setting-row';const value=typeof settings[key]==='boolean'?(settings[key]?'ON':'OFF'):String(settings[key]).toUpperCase();row.innerHTML=`<span>${name}</span><button>${value}</button>`;row.querySelector('button').onclick=()=>{if(typeof settings[key]==='boolean')settings[key]=!settings[key];else{const vals=['full','reduced','minimal'];settings[key]=vals[(vals.indexOf(settings[key])+1)%vals.length]}saveSettings();renderSettings()};host.appendChild(row)}}

function towerMods(def,t){const lvl=t?.level||0, dmg=(1+profile.damage*.02)*(1+lvl*.18),rng=(1+profile.range*.015)*(1+lvl*.08),rate=(1+profile.rate*.015)*(1+lvl*.10);return{damage:def.damage*dmg,range:def.range*rng,rate:def.rate/rate};}
function towerCost(type){const base=TOWERS[type].cost;if(!state?.endless)return base;const n=state.towers.filter(t=>t.type===type).length;return Math.ceil(base*(1+Math.min(.8,n*.04)));}
function makeTowerButtons(){const entries=Object.entries(TOWERS),pages=Math.ceil(entries.length/towerPerPage);towerPage=Math.max(0,Math.min(pages-1,towerPage));const host=$('#towerButtons');host.innerHTML='';for(const [k,d] of entries.slice(towerPage*towerPerPage,(towerPage+1)*towerPerPage)){const b=document.createElement('button');b.className='tower-btn'+(k===selectedTower?' selected':'');b.innerHTML=`${d.name} — $${towerCost(k)}<small>${d.desc}</small>`;b.onclick=()=>{selectedTower=k;hideUnitPanel();makeTowerButtons()};host.appendChild(b)}$('#towerPageText').textContent=`${towerPage+1}/${pages}`;$('#prevTowerPage').disabled=towerPage===0;$('#nextTowerPage').disabled=towerPage===pages-1;}

function startLevel(index,direct=null,forced=null){const levels=allLevels(),lvl=direct||levels[index];if(!lvl)return;const diff=forced||rollDiff(),base=Math.max(20,Math.min(9999,profile.baseHP));const routes=pathsOf(lvl);state={lvl,levelIndex:index,cash:Math.round(lvl.startCash*(diff.cash||1)),wave:-1,waveRunning:false,spawnLeft:0,spawnTimer:0,currentWave:null,enemies:[],towers:[],bullets:[],particles:[],floaters:[],shockwaves:[],lasers:[],elapsed:0,ended:false,autoStarted:false,intermission:0,diff,paused:false,speed:1,endless:endless.active,selectedPlaced:null,pointer:{x:-999,y:-999},baseHPs:routes.map(()=>base),baseMax:base,routes};$('#levelNumber').textContent=direct?'??':String(lvl.id||index+1).padStart(2,'0');$('#levelName').textContent=endless.active?`ENDLESS // ${lvl.name}`:lvl.name;$('#resultOverlay').classList.add('hidden');$('#endlessStat').classList.toggle('show',endless.active);showScreen('gameScreen');makeTowerButtons();syncHud();fitArena();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);toast('PLACE AT LEAST 2 UNITS',1400);}
function syncHud(){if(!state)return;$('#hpText').textContent=state.baseHPs.length===1?Math.ceil(state.baseHPs[0]):state.baseHPs.map((x,i)=>`B${i+1}:${Math.ceil(x)}`).join(' ');$('#cashText').textContent=Math.floor(state.cash);$('#waveText').textContent=state.endless?`${Math.max(0,state.wave+1)}/∞`:`${Math.max(0,state.wave+1)}/${state.lvl.waves.length}`;$('#difficultyText').textContent=`${DIFF[selectedDifficulty].name} ${Math.round(state.diff.hp*100)}%`;$('#endlessClearedText').textContent=endless.cleared;refreshPoints();const can=!state.autoStarted&&!state.ended&&state.towers.length>=2;$('#waveBtn').disabled=!can;$('#waveBtn').textContent=state.ended?'SESSION ENDED':!state.autoStarted?'READY!':state.intermission>0?`NEXT WAVE IN ${state.intermission.toFixed(1)}s`:state.waveRunning?`AUTO // WAVE ${state.wave+1}`:'AUTO WAVES ON';$('#pauseBtn').textContent=state.paused?'RESUME':'PAUSE';$$('.speedBtn').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===state.speed));}

function pathData(path){const pts=path.map(([x,y])=>({x:x*W,y:y*H}));let total=0;const seg=[];for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],len=Math.hypot(b.x-a.x,b.y-a.y);seg.push({a,b,len,start:total});total+=len}return{pts,seg,total};}
function posOn(pathIndex,p){const d=pathData(state.routes[pathIndex]),dist=p*d.total,s=d.seg.find(x=>dist<=x.start+x.len)||d.seg[d.seg.length-1],t=Math.max(0,Math.min(1,(dist-s.start)/Math.max(1,s.len)));return{x:s.a.x+(s.b.x-s.a.x)*t,y:s.a.y+(s.b.y-s.a.y)*t};}
function randomEndlessWave(){const c=endless.cleared,maxId=c<4?3:c<8?5:c<12?10:20,pool=[];for(const l of UNRENDERED_LEVELS){if(l.id>maxId)continue;l.waves.forEach((w,wi)=>{if(c<3&&w.boss)return;pool.push({w,l,key:`${l.id}:${wi}`})})}let choices=pool.filter(x=>x.key!==endless.lastWaveKey);if(!choices.length)choices=pool;const p=choices[Math.floor(Math.random()*choices.length)];endless.lastWaveKey=p.key;return p;}
function beginWave(){if(!state||state.waveRunning||state.ended)return;if(!state.endless&&state.wave>=state.lvl.waves.length-1)return;state.wave++;let w;if(state.endless){const p=randomEndlessWave();w={...p.w};toast(`${w.boss?'BOSS // ':''}${p.l.name}`,1000)}else{w=state.lvl.waves[state.wave];toast(w.boss?'BOSS WAVE':`WAVE ${state.wave+1}`)}w={...w,count:Math.max(1,Math.round(w.count*(state.diff.count||1))),gap:w.gap*(state.diff.gap||1)};state.currentWave=w;state.spawnLeft=w.count;state.spawnTimer=0;state.waveRunning=true;syncHud();}
function startWaves(){if(!state||state.autoStarted||state.towers.length<2)return;state.autoStarted=true;beginWave();}

function spawnEnemy(w){const type=w.type||'enemy',def=ENEMIES[type]||ENEMIES.enemy,pathIndex=state.routes.length>1?Math.floor(Math.random()*state.routes.length):0,pos=posOn(pathIndex,0);let hp=w.hp*def.hp*state.diff.hp,speed=w.speed*def.speed*state.diff.speed;const armorChance=Math.min(.75,(state.diff.armor||0)+(state.lvl.world===2?.06:0)),barChance=Math.min(.65,(state.diff.bars||0)+(state.lvl.world===2?.05:0));const armor=Math.random()<armorChance?(.12+Math.random()*.28):0,bars=Math.random()<barChance?(2+Math.floor(Math.random()*(state.diff===DIFF.fun?3:2))):1;const e={x:pos.x,y:pos.y,pathIndex,progress:0,hp,maxHp:hp,barHp:hp,bars,barsLeft:bars,speed,baseSpeed:speed,reward:w.reward*def.reward,scale:(w.scale||1)*def.scale,boss:!!w.boss,type,def,armor,slowTimer:0,flash:0,dead:false,age:0,shield:type==='thinkingcrystals'?hp*.25:0,maxShield:type==='thinkingcrystals'?hp*.25:0,bleedTime:0,bleedTick:0,bleedDamage:0,healTick:1.5,phaseTick:1};state.enemies.push(e);shock(e.x,e.y,42,def.color);}
function leakDamage(e){const lo=e.boss?3:1,hi=e.boss?5:5;return Math.floor(lo+Math.random()*(hi-lo+1));}
function update(dt){if(!state||state.ended||state.paused)return;dt*=state.speed;state.elapsed+=dt;if(state.autoStarted&&state.intermission>0&&!state.waveRunning){state.intermission=Math.max(0,state.intermission-dt);if(state.intermission<=0)beginWave()}
 if(state.waveRunning){state.spawnTimer-=dt;while(state.spawnLeft>0&&state.spawnTimer<=0){spawnEnemy(state.currentWave);state.spawnLeft--;state.spawnTimer+=state.currentWave.gap}}
 for(const e of state.enemies){if(e.dead)continue;e.age+=dt;e.slowTimer=Math.max(0,e.slowTimer-dt);e.flash=Math.max(0,e.flash-dt);if(e.bleedTime>0){e.bleedTime-=dt;e.bleedTick-=dt;if(e.bleedTick<=0){e.bleedTick=.5;damageEnemy(e,e.bleedDamage,0,true)}}if(e.def.heal){e.healTick-=dt;if(e.healTick<=0){e.healTick=1.6;for(const o of state.enemies)if(!o.dead&&o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<95)o.hp=Math.min(o.maxHp,o.hp+o.maxHp*.05)}}let shift=1;if(e.type==='changeme00')shift=.78+Math.abs(Math.sin(e.age*2.1))*.48;if(e.def.phase){e.phaseTick-=dt;if(e.phaseTick<=0){e.phaseTick=.8+Math.random()*1.2;e.progress=Math.min(.96,e.progress+.012)}}const len=pathData(state.routes[e.pathIndex]).total,eSp=e.baseSpeed*shift*(e.slowTimer>0?.57:1);e.progress+=(eSp*600/Math.max(1,len))*dt;const p=posOn(e.pathIndex,e.progress);e.x=p.x;e.y=p.y;if(e.progress>=1){e.dead=true;const dmg=leakDamage(e);state.baseHPs[e.pathIndex]-=dmg;if(settings.shake)shake=Math.max(shake,8);floater(e.x-45,e.y-20,`-${dmg} BASE`,'#ff7379');if(state.baseHPs[e.pathIndex]<=0)finish(false)}}
 for(const t of state.towers){t.cd-=dt;const def=TOWERS[t.type],mods=towerMods(def,t);if(t.cd>0)continue;const targets=state.enemies.filter(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<=mods.range).sort((a,b)=>b.progress-a.progress);if(!targets.length)continue;t.cd=mods.rate;if(def.aoeSelf){targets.forEach(e=>damageEnemy(e,mods.damage,0));shock(t.x,t.y,mods.range,'#9d72dd');continue}if(def.rail){fireRail(t,mods);continue}const target=targets[0];state.bullets.push({x:t.x,y:t.y,target,speed:def.projectile||500,damage:mods.damage,type:t.type,splash:def.splash||0,slow:def.slow||0,slowTime:def.slowTime||1.2,bleed:def.bleed||null,lob:!!def.lob,pierce:def.pierce||0,chain:def.chain||0,armorBreak:def.armorBreak||0,dead:false});}
 for(const b of state.bullets){if(b.dead||b.target.dead){b.dead=true;continue}const dx=b.target.x-b.x,dy=b.target.y-b.y,d=Math.hypot(dx,dy);if(d<12){hitBullet(b);continue}const st=Math.min(d,b.speed*dt);b.x+=dx/Math.max(1,d)*st;b.y+=dy/Math.max(1,d)*st;}
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}for(const f of state.floaters)f.life-=dt;for(const s of state.shockwaves){s.r+=s.max*dt*3;s.life-=dt}for(const l of state.lasers)l.life-=dt;state.enemies=state.enemies.filter(e=>!e.dead);state.bullets=state.bullets.filter(b=>!b.dead);state.particles=state.particles.filter(p=>p.life>0).slice(-700);state.floaters=state.floaters.filter(f=>f.life>0).slice(-220);state.shockwaves=state.shockwaves.filter(s=>s.life>0).slice(-100);state.lasers=state.lasers.filter(l=>l.life>0).slice(-80);shake*=Math.pow(.02,dt);
 if(state.waveRunning&&state.spawnLeft===0&&state.enemies.length===0){state.waveRunning=false;if(!state.endless&&state.wave===state.lvl.waves.length-1)finish(true);else{if(state.endless){endless.cleared++;if(endless.cleared%10===0){profile.points+=5;saveProfile();toast('+5 POINTS // ENDLESS MILESTONE')}}let bonus=35+Math.min(state.wave,20)*10;if(state.endless&&endless.cleared>25)bonus*=Math.max(.45,1-(endless.cleared-25)*.012);state.cash+=Math.round(bonus);state.intermission=3;syncHud();}}
 syncHud();}
function damageEnemy(e,raw,slow=0,silent=false){if(e.dead)return;let dmg=raw;if(e.armor>0)dmg*=1-e.armor;if(e.def.reflect)dmg*=1-e.def.reflect;if(e.shield>0){const x=Math.min(e.shield,dmg);e.shield-=x;dmg-=x;if(dmg<=0)return}e.hp-=dmg;e.flash=.07;if(slow)e.slowTimer=Math.max(e.slowTimer,1.2);if(settings.damageNumbers&&!silent)floater(e.x-8,e.y-28,`-${Math.ceil(dmg)}`,'#fff');if(e.hp<=0){if(e.barsLeft>1){e.barsLeft--;e.hp=e.maxHp;shock(e.x,e.y,50,'#ffd15c');floater(e.x-15,e.y-34,`${e.barsLeft} BAR${e.barsLeft>1?'S':''}`,'#ffd15c');return}killEnemy(e)}}
function killEnemy(e){e.dead=true;let mult=1;if(state.endless&&endless.cleared>25)mult=Math.max(.45,1-(endless.cleared-25)*.012);const reward=Math.max(1,Math.round(e.reward*(state.lvl.rewardScale||1)*mult));state.cash+=reward;if(settings.damageNumbers)floater(e.x-15,e.y-30,`+$${reward}`,'#75dcff');burst(e.x,e.y,e.boss?28:10,e.def.color);if(e.def.split&&!e.boss&&!e.noSplit){for(let i=0;i<2;i++){const n={...e,dead:false,noSplit:true,hp:e.maxHp*.35,maxHp:e.maxHp*.35,bars:1,barsLeft:1,scale:e.scale*.65,reward:e.reward*.25,progress:Math.max(0,e.progress-.01*i)};const p=posOn(n.pathIndex,n.progress);n.x=p.x;n.y=p.y;state.enemies.push(n)}}}
function hitBullet(b){b.dead=true;let targets=b.splash?state.enemies.filter(e=>!e.dead&&Math.hypot(e.x-b.target.x,e.y-b.target.y)<=b.splash):[b.target];if(b.chain){targets=[b.target,...state.enemies.filter(e=>!e.dead&&e!==b.target).sort((a,c)=>Math.hypot(a.x-b.target.x,a.y-b.target.y)-Math.hypot(c.x-b.target.x,c.y-b.target.y)).slice(0,b.chain-1)]}for(const e of targets){if(b.armorBreak)e.armor=Math.max(0,e.armor-b.armorBreak);damageEnemy(e,b.damage,b.slow);if(b.slow)e.slowTimer=Math.max(e.slowTimer,b.slowTime||1.2);if(b.bleed&&!e.dead){e.bleedTime=Math.max(e.bleedTime,b.bleed.duration);e.bleedDamage=b.bleed.damage;e.bleedTick=.5}}burst(b.target.x,b.target.y,6,TOWERS[b.type]?.proc||'#8edfff');}
function fireRail(t,mods){const target=state.enemies.filter(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<=mods.range).sort((a,b)=>b.progress-a.progress)[0];if(!target)return;const dx=target.x-t.x,dy=target.y-t.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len,x2=t.x+ux*W*1.5,y2=t.y+uy*W*1.5;for(const e of state.enemies){const px=e.x-t.x,py=e.y-t.y,proj=px*ux+py*uy,perp=Math.abs(px*uy-py*ux);if(proj>=0&&proj<mods.range*1.5&&perp<28)damageEnemy(e,mods.damage,0)}state.lasers.push({x1:t.x,y1:t.y,x2,y2,life:.2,maxLife:.2});if(settings.flashes)$('#screenFlash').classList.add('on'),setTimeout(()=>$('#screenFlash').classList.remove('on'),80);if(settings.shake)shake=12;tone(900,.18,.02,'sawtooth',90);}

function distanceToPaths(x,y){let min=Infinity;for(const path of state.routes){const p=path.map(([a,b])=>({x:a*W,y:b*H}));for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],vx=b.x-a.x,vy=b.y-a.y,den=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((x-a.x)*vx+(y-a.y)*vy)/den));min=Math.min(min,Math.hypot(x-(a.x+vx*t),y-(a.y+vy*t)))}}return min;}
function placeTower(x,y){const def=TOWERS[selectedTower],cost=towerCost(selectedTower);if(state.cash<cost)return toast('NOT ENOUGH CASH');if(distanceToPaths(x,y)<48)return toast('TOO CLOSE TO THE PATH');if(state.towers.some(t=>Math.hypot(t.x-x,t.y-y)<62))return toast('TOO CLOSE TO ANOTHER UNIT');if(x<32||x>W-32||y<32||y>H-32)return;state.cash-=cost;state.towers.push({x,y,type:selectedTower,paid:cost,level:0,cd:def.rail?def.rate:Math.random()*.1});burst(x,y,8,'#74d8ff');makeTowerButtons();syncHud();}
function showUnitPanel(t){state.selectedPlaced=t;const d=TOWERS[t.type],m=towerMods(d,t),refund=Math.floor((t.paid||d.cost)*Math.min(.9,.70+profile.sell*.02)),upCost=Math.round((d.cost*.65)*(t.level+1));$('#unitPanelName').textContent=`${d.name} LV.${t.level+1}`;$('#unitPanelStats').textContent=`${Math.round(m.damage)} dmg // ${Math.round(m.range)} range // ${m.rate.toFixed(2)}s`;$('#sellUnitBtn').textContent=state.diff.noSell?'NO SELLING':`SELL $${refund}`;$('#sellUnitBtn').disabled=!!state.diff.noSell;$('#upgradeUnitBtn').textContent=`UPGRADE $${upCost}`;$('#unitPanel').classList.remove('hidden');}
function hideUnitPanel(){$('#unitPanel').classList.add('hidden');if(state)state.selectedPlaced=null;}
function sellSelected(){const t=state?.selectedPlaced;if(!t||state.diff.noSell)return toast('SELLING IS OFF IN FUN MODE');const d=TOWERS[t.type],refund=Math.floor((t.paid||d.cost)*Math.min(.9,.70+profile.sell*.02));const doIt=()=>{state.towers.splice(state.towers.indexOf(t),1);state.cash+=refund;hideUnitPanel();syncHud();makeTowerButtons()};if(settings.confirmSell){if(confirm(`Sell ${d.name} for $${refund}?`))doIt()}else doIt();}
function upgradeSelected(){const t=state?.selectedPlaced;if(!t)return;const d=TOWERS[t.type],cost=Math.round((d.cost*.65)*(t.level+1));if(state.cash<cost)return toast('NOT ENOUGH CASH');if(t.level>=5)return toast('MAX LEVEL');state.cash-=cost;t.level++;showUnitPanel(t);syncHud();}

function burst(x,y,n,color='#f0222b'){const amount=settings.particles==='minimal'?Math.ceil(n*.25):settings.particles==='reduced'?Math.ceil(n*.55):n;for(let i=0;i<amount;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*180;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.4,color:typeof color==='string'?color:'#fff',size:2+Math.random()*3})}}
function floater(x,y,text,color){state.floaters.push({x,y,text,color,life:.8})}function shock(x,y,max,color){state.shockwaves.push({x,y,r:4,max,life:.25,color})}
function draw(){if(!state)return;ctx.save();const sx=settings.shake?(Math.random()-.5)*shake:0,sy=settings.shake?(Math.random()-.5)*shake:0;ctx.translate(sx,sy);ctx.fillStyle='#080a0f';ctx.fillRect(-20,-20,W+40,H+40);ctx.strokeStyle='rgba(255,255,255,.035)';for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
 state.routes.forEach((path,pi)=>{const p=path.map(([x,y])=>({x:x*W,y:y*H}));ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='rgba(240,34,43,.13)';ctx.lineWidth=58;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.stroke();ctx.strokeStyle=pi?'#ff8a3d':'#f0222b';ctx.lineWidth=4;ctx.setLineDash([18,10,4,8]);ctx.lineDashOffset=state.elapsed*-35;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.stroke();ctx.setLineDash([]);const end=p[p.length-1];ctx.fillStyle=pi?'#ff8a3d':'#f0222b';ctx.fillRect(W-12,end.y-30,12,60);ctx.fillStyle='#fff';ctx.font='bold 12px Arial';ctx.fillText(`BASE ${pi+1} ${Math.max(0,Math.ceil(state.baseHPs[pi]))}`,W-105,Math.max(16,Math.min(H-8,end.y-38)));});
 for(const t of state.towers){if(state.selectedPlaced===t){const m=towerMods(TOWERS[t.type],t);ctx.strokeStyle='rgba(255,255,255,.4)';ctx.beginPath();ctx.arc(t.x,t.y,m.range,0,Math.PI*2);ctx.stroke()}drawTower(t)}for(const b of state.bullets){ctx.fillStyle=TOWERS[b.type]?.proc||'#75dcff';ctx.beginPath();ctx.arc(b.x,b.y,4,0,Math.PI*2);ctx.fill()}for(const e of state.enemies)drawEnemy(e);for(const s of state.shockwaves){ctx.globalAlpha=Math.max(0,s.life/.25);ctx.strokeStyle=s.color;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(const l of state.lasers){ctx.globalAlpha=Math.max(0,l.life/l.maxLife);ctx.strokeStyle='#dffaff';ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(l.x1,l.y1);ctx.lineTo(l.x2,l.y2);ctx.stroke();ctx.strokeStyle='#3997ff';ctx.lineWidth=4;ctx.stroke()}ctx.globalAlpha=1;for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life/.6);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of state.floaters){ctx.globalAlpha=Math.min(1,f.life*2);ctx.fillStyle=f.color;ctx.font='bold 14px Arial';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;if(state.pointer.x>0&&!state.ended){const d=TOWERS[selectedTower],m=towerMods(d,null);ctx.strokeStyle=distanceToPaths(state.pointer.x,state.pointer.y)>=48?'rgba(10,161,232,.48)':'rgba(240,34,43,.48)';ctx.beginPath();ctx.arc(state.pointer.x,state.pointer.y,m.range,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.5;drawUnitVisual(selectedTower,state.pointer.x,state.pointer.y,50);ctx.globalAlpha=1}ctx.restore();}
function drawContained(im,x,y,w,h){const ar=im.naturalWidth/Math.max(1,im.naturalHeight);let ww=w,hh=ww/ar;if(hh>h){hh=h;ww=hh*ar}ctx.drawImage(im,x-ww/2,y-hh/2,ww,hh)}
function drawUnitVisual(type,x,y,size){const im=images[type];if(im?.complete&&im.naturalWidth){drawContained(im,x,y,size,size);return}const d=TOWERS[type];ctx.save();ctx.translate(x,y);ctx.fillStyle=d?.proc||'#6ca6ff';ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.fillRect(-size*.42,-size*.42,size*.84,size*.84);ctx.strokeRect(-size*.42,-size*.42,size*.84,size*.84);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-size*.25,0);ctx.lineTo(size*.25,0);ctx.moveTo(0,-size*.25);ctx.lineTo(0,size*.25);ctx.stroke();ctx.restore();}
function drawTower(t){const d=TOWERS[t.type];ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='rgba(255,255,255,.06)';ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.fill();drawUnitVisual(t.type,0,0,56);ctx.fillStyle='#d7dbe6';ctx.font='bold 8px Arial';ctx.textAlign='center';ctx.fillText(d.name,0,39);ctx.fillText(`LV${t.level+1}`,0,49);if(d.rail){const charge=1-Math.max(0,t.cd)/towerMods(d,t).rate;ctx.fillStyle='#111827';ctx.fillRect(-28,52,56,4);ctx.fillStyle='#56c9ff';ctx.fillRect(-28,52,56*Math.max(0,Math.min(1,charge)),4)}ctx.restore();}
function drawEnemy(e){const s=54*e.scale;ctx.save();ctx.translate(e.x,e.y);const im=images[e.type];if(im?.complete&&im.naturalWidth)drawContained(im,0,0,s,s);else drawProcEnemy(e,s);if(settings.healthBars){const w=Math.max(34,s*.9),y=-s/2-10;ctx.fillStyle='#25090b';ctx.fillRect(-w/2,y,w,5);ctx.fillStyle=e.def.color;ctx.fillRect(-w/2,y,w*Math.max(0,e.hp/e.maxHp),5);for(let i=1;i<e.barsLeft;i++){ctx.fillStyle='#ffd15c';ctx.fillRect(-w/2,y-5*i,w,2)}if(e.armor>0){ctx.strokeStyle='#bfc7d4';ctx.strokeRect(-w/2-2,y-2,w+4,9)}if(e.shield>0){ctx.fillStyle='#9de8ff';ctx.fillRect(-w/2,y-7,w*(e.shield/e.maxShield),3)}}ctx.restore();}
function drawProcEnemy(e,s){ctx.fillStyle=e.def.color;ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();const p=e.def.proc;if(p==='clip'){ctx.arc(0,0,s*.25,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(8,0,s*.18,0,Math.PI*2);ctx.stroke();return}if(p==='clot'){ctx.arc(0,0,s*.42,0,Math.PI*2);ctx.fill();ctx.stroke();return}if(p==='zip'){ctx.fillRect(-s*.38,-s*.3,s*.76,s*.6);ctx.strokeRect(-s*.38,-s*.3,s*.76,s*.6);for(let y=-s*.22;y<s*.25;y+=8){ctx.moveTo(-8,y);ctx.lineTo(8,y);ctx.stroke()}return}if(p==='mirror'){ctx.rotate(Math.PI/4);ctx.fillRect(-s*.32,-s*.32,s*.64,s*.64);ctx.strokeRect(-s*.32,-s*.32,s*.64,s*.64);return}if(p==='plus'){ctx.fillRect(-8,-s*.36,16,s*.72);ctx.fillRect(-s*.36,-8,s*.72,16);return}if(p==='split'){ctx.moveTo(-s*.4,s*.3);ctx.lineTo(0,-s*.4);ctx.lineTo(s*.4,s*.3);ctx.closePath();ctx.fill();ctx.stroke();return}if(p==='ghost'){ctx.globalAlpha=.65;ctx.arc(0,0,s*.38,Math.PI,0);ctx.lineTo(s*.38,s*.3);ctx.lineTo(s*.18,s*.18);ctx.lineTo(0,s*.3);ctx.lineTo(-s*.18,s*.18);ctx.lineTo(-s*.38,s*.3);ctx.closePath();ctx.fill();ctx.stroke();return}if(p==='leech'){ctx.ellipse(0,0,s*.38,s*.2,0,0,Math.PI*2);ctx.fill();ctx.stroke();return}if(p==='brick'){ctx.fillRect(-s*.4,-s*.28,s*.8,s*.56);ctx.strokeRect(-s*.4,-s*.28,s*.8,s*.56);ctx.moveTo(0,-s*.28);ctx.lineTo(0,s*.28);ctx.stroke();return}ctx.arc(0,0,s*.36,0,Math.PI*2);ctx.fill();ctx.stroke();}

function finish(win){if(!state||state.ended)return;state.ended=true;state.waveRunning=false;syncHud();if(win&&!state.endless){const key=`${state.lvl.world||1}-${state.lvl.id}`,first=!profile.clears[key],gain=10+(state.lvl.world||1)*5+Math.min(20,state.lvl.id||1)+(first?20:0);profile.points+=gain;profile.clears[key]=(profile.clears[key]||0)+1;saveProfile();$('#resultTitle').textContent='LEVEL CLEARED';$('#resultText').textContent=`+${gain} Points${first?' // FIRST CLEAR BONUS':''}`;}else{$('#resultTitle').textContent='DEFEAT';$('#resultText').textContent=state.endless?`Waves cleared: ${endless.cleared}`:'A base ran out of HP.'}$('#resultOverlay').classList.remove('hidden');}
function startEndless(){const levels=UNRENDERED_LEVELS,idx=Math.floor(Math.random()*levels.length);endless={active:true,cleared:0,lastWaveKey:''};startLevel(idx);}
function fitArena(){const wrap=$('#gameWrap'),top=$('.game-topbar'),controls=$('.control-panel');if(!wrap)return;const portrait=innerHeight>innerWidth&&innerWidth<=700;const maxW=Math.max(260,innerWidth-(portrait?12:20));let w;if(portrait){w=Math.floor(Math.min(W,maxW));}else{const maxH=Math.max(180,innerHeight-(top?.offsetHeight||0)-(controls?.offsetHeight||0)-30);w=Math.floor(Math.min(W,maxW,maxH*(W/H)));}wrap.style.width=w+'px';wrap.style.height=Math.floor(w*H/W)+'px';}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();if($('#gameScreen').classList.contains('active'))raf=requestAnimationFrame(loop)}
function canvasPoint(e,c=canvas){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*c.width,y:(e.clientY-r.top)/r.height*c.height}}

function makeDesignerLevel(){const count=Math.max(1,Math.min(20,+$('#designWaves').value||5)),waves=[];for(let i=0;i<count;i++)waves.push({count:8+i*2,hp:45+i*20,speed:.065+i*.002,gap:Math.max(.3,.7-i*.03),reward:12+i*2,boss:i===count-1});return{id:Date.now(),world:1,name:$('#designName').value||'Custom Level',description:'Custom level.',tint:$('#designTint').value,startCash:+$('#designCash').value||400,baseHP:20,rewardScale:1,path:designerPath.map(p=>[+p[0].toFixed(4),+p[1].toFixed(4)]),waves,custom:true};}
function drawDesigner(){if(!$('#designerScreen').classList.contains('active'))return;const cw=dCanvas.width,ch=dCanvas.height;dctx.fillStyle='#090b11';dctx.fillRect(0,0,cw,ch);if(designerPath.length){dctx.strokeStyle=$('#designTint').value||'#64e4ff';dctx.lineWidth=4;dctx.beginPath();dctx.moveTo(designerPath[0][0]*cw,designerPath[0][1]*ch);for(let i=1;i<designerPath.length;i++)dctx.lineTo(designerPath[i][0]*cw,designerPath[i][1]*ch);dctx.stroke()}$('#designerStatus').textContent=`${designerPath.length} path points.`;}

canvas.addEventListener('pointermove',e=>{if(state)state.pointer=canvasPoint(e)});canvas.addEventListener('pointerleave',()=>{if(state)state.pointer={x:-999,y:-999}});canvas.addEventListener('pointerdown',e=>{if(!state||state.ended)return;const p=canvasPoint(e),hit=[...state.towers].reverse().find(t=>Math.hypot(t.x-p.x,t.y-p.y)<=36);if(hit)return showUnitPanel(hit);hideUnitPanel();placeTower(p.x,p.y)});
dCanvas.addEventListener('pointerdown',e=>{const p=canvasPoint(e,dCanvas);designerPath.push([p.x/dCanvas.width,p.y/dCanvas.height]);drawDesigner()});
$('#undoPointBtn').onclick=()=>{designerPath.pop();drawDesigner()};$('#clearPathBtn').onclick=()=>{designerPath=[];drawDesigner()};$('#designTint').oninput=drawDesigner;$('#testDesignBtn').onclick=()=>{if(designerPath.length<2)return toast('NEED 2 PATH POINTS');startLevel(-1,makeDesignerLevel())};$('#saveDesignBtn').onclick=()=>{if(designerPath.length<2)return;customLevels.push(makeDesignerLevel());localStorage.setItem('unrendered_custom_levels',JSON.stringify(customLevels));renderLevels();toast('SAVED')};
$('#prevTowerPage').onclick=()=>{towerPage--;makeTowerButtons()};$('#nextTowerPage').onclick=()=>{towerPage++;makeTowerButtons()};$('#sellUnitBtn').onclick=sellSelected;$('#upgradeUnitBtn').onclick=upgradeSelected;$('#closeUnitPanelBtn').onclick=hideUnitPanel;$('#waveBtn').onclick=startWaves;
$('#pauseBtn').onclick=()=>{if(!state)return;state.paused=!state.paused;syncHud()};$$('.speedBtn').forEach(b=>b.onclick=()=>{if(!state)return;state.speed=Number(b.dataset.speed);syncHud()});
$('#playBtn').onclick=()=>{endless.active=false;renderLevels();showScreen('levelsScreen')};$('#endlessBtn').onclick=startEndless;$('#upgradesBtn').onclick=()=>showScreen('upgradesScreen');$('#settingsBtn').onclick=()=>showScreen('settingsScreen');$('#designerBtn').onclick=()=>showScreen('designerScreen');$('#howBtn').onclick=()=>showScreen('helpScreen');$$('[data-back="home"]').forEach(b=>b.onclick=()=>{endless.active=false;showScreen('homeScreen')});$('#exitGameBtn').onclick=()=>{endless.active=false;renderLevels();showScreen('levelsScreen')};$('#resultLevelsBtn').onclick=()=>{endless.active=false;renderLevels();showScreen('levelsScreen')};$('#retryBtn').onclick=()=>{const d=state.diff;endless.active=false;startLevel(state.levelIndex,state.lvl,d)};
addEventListener('resize',fitArena);addEventListener('orientationchange',()=>setTimeout(fitArena,120));renderLevels();makeTowerButtons();renderSettings();renderUpgrades();refreshPoints();drawDesigner();
})();
